name: Publish Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build & Publish Docker image
        run: |
          docker build . -t ghcr.io/nanaimo2013/nans-surf-cs2:latest -f docker/RT3-Dockerfile
          docker push ghcr.io/nanaimo2013/nans-surf-cs2:latest 