name: Publish Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Prepare directories for Docker build
        run: |
          # Create empty directories to prevent Docker build errors if they don't exist
          mkdir -p gamefiles/plugins/compiled
          mkdir -p gamefiles/configs/core
          mkdir -p gamefiles/configs/sourcemod/surf
          touch gamefiles/configs/core/.gitkeep
          touch gamefiles/configs/sourcemod/.gitkeep
          touch gamefiles/configs/sourcemod/surf/.gitkeep
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/RT3-Dockerfile
          push: true
          tags: |
            ghcr.io/nanaimo2013/nans-surf-cs2:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max 